In [35]:
import pandas as pd
import json
import requests

In [36]:
username = '7f45ea45a1833ac7e127047a738e4264' # also the token
password = 'api_token'
URL = 'https://api.track.toggl.com/api/v8/workspaces'

response = requests.get(URL, auth = (username, password) )

In [37]:
thing = response.json()
type(thing)

list

In [38]:
id_ = thing[0]['id'] # go through other enties to get other workspaces
id_

4482767

In [39]:
URL = 'https://api.track.toggl.com/reports/api/v2/details?workspace_id=4482767&since=2020-08-1&until=2020-10-1&user_agent=aryaatharva18@gmail.com'
response = requests.get(URL, auth = (username, password) )
# response.json()

In [40]:

cols = [
#  'id',
#  'pid',
#  'tid',
#  'uid',
 'description',
 'start',
 'end',
 'updated',
 'dur',
#  'user',
#  'use_stop',
#  'client',
 'project',
#  'project_color',
 'project_hex_color'
#  'task',
#  'billable',
#  'is_billable',
#  'cur',
#  'tags'
]
from collections import defaultdict
df_raw = defaultdict(list)

In [41]:
ind = 1
data = []
data_in = [0]
while len(data_in) != 0:
    URL = URL + '&page=' + str(ind)
    response = requests.get(URL, auth = (username, password)).json()
    data_in = response['data']
    data += data_in
    for col in cols:
        for item in data_in:
            df_raw[col].append(item[col])
    ind += 1

In [64]:
df = pd.DataFrame.from_dict(df_raw)
df.head(20)

,description,start,end,updated,dur,project,project_hex_color
0,ED Assignment,2020-10-01T21:00:00+05:30,2020-10-01T22:00:00+05:30,2020-10-01T22:08:44+05:30,3600000,College Work,#525266
1,Hands on ML,2020-10-01T16:00:00+05:30,2020-10-01T18:00:00+05:30,2020-10-01T20:33:23+05:30,7200000,Books and Courses,#d92b2b
2,Hands on ML,2020-10-01T13:40:00+05:30,2020-10-01T14:40:00+05:30,2020-10-01T14:59:40+05:30,3600000,Books and Courses,#d92b2b
3,Hands on ML,2020-10-01T09:55:00+05:30,2020-10-01T11:55:00+05:30,2020-10-01T13:21:48+05:30,7200000,Books and Courses,#d92b2b
4,Hands on ML,2020-09-30T20:55:00+05:30,2020-09-30T22:10:00+05:30,2020-10-01T01:17:55+05:30,4500000,Books and Courses,#d92b2b
5,Hands on ML,2020-09-30T15:55:00+05:30,2020-09-30T17:55:00+05:30,2020-09-30T19:12:59+05:30,7200000,Books and Courses,#d92b2b
6,Hands on ML,2020-09-30T13:55:00+05:30,2020-09-30T15:00:00+05:30,2020-09-30T19:12:46+05:30,3900000,Books and Courses,#d92b2b
7,Hands on ML,2020-09-30T10:43:53+05:30,2020-09-30T11:43:53+05:30,2020-09-30T19:12:17+05:30,3600000,Books and Courses,#d92b2b
8,NLP Course 2,2020-09-29T23:28:05+05:30,2020-09-29T23:34:56+05:30,2020-09-30T12:12:11+05:30,411000,Books and Courses,#d92b2b
9,NLP Course 2,2020-09-29T23:28:03+05:30,2020-09-29T23:28:04+05:30,2020-09-30T12:12:11+05:30,1000,Books and Courses,#d92b2b
10,NLP Course 2,2020-09-29T23:27:57+05:30,2020-09-29T23:28:02+05:30,2020-09-30T12:12:10+05:30,5000,Books and Courses,#d92b2b
11,NLP Course 2,2020-09-29T23:27:57+05:30,2020-09-29T23:27:58+05:30,2020-09-30T12:12:10+05:30,1000,Books and Courses,#d92b2b
12,NLP Course 2,2020-09-29T22:48:16+05:30,2020-09-29T23:19:29+05:30,2020-09-30T12:12:10+05:30,1873000,Books and Courses,#d92b2b
13,NLP Course 2,2020-09-29T22:13:55+05:30,2020-09-29T22:37:57+05:30,2020-09-30T12:12:10+05:30,1442000,Books and Courses,#d92b2b
14,NLP Course 2,2020-09-29T21:40:52+05:30,2020-09-29T22:04:05+05:30,2020-09-30T12:12:10+05:30,1393000,Books and Courses,#d92b2b
15,NLP Course 2,2020-09-29T21:13:18+05:30,2020-09-29T21:35:08+05:30,2020-09-30T12:12:10+05:30,1310000,Books and Courses,#d92b2b
16,NLP Course 2,2020-09-29T20:05:00+05:30,2020-09-29T20:15:00+05:30,2020-09-30T12:12:10+05:30,600000,Books and Courses,#d92b2b
17,NLP Course 2,2020-09-29T19:41:23+05:30,2020-09-29T19:59:38+05:30,2020-09-30T12:12:10+05:30,1095000,Books and Courses,#d92b2b
18,NLP Course 2,2020-09-29T18:50:00+05:30,2020-09-29T19:20:00+05:30,2020-09-30T12:12:10+05:30,1800000,Books and Courses,#d92b2b
19,NLP Course 2,2020-09-29T17:49:05+05:30,2020-09-29T18:36:11+05:30,2020-09-30T12:12:10+05:30,2826000,Books and Courses,#d92b2b

In [68]:
sum(df['dur'].tolist()[4:8])

19200000

In [13]:
import datetime

In [43]:
(datetime.datetime(2020, 8, 7)-datetime.datetime.strptime(df['updated'].tolist()[-1].split("+")[0], '%Y-%m-%dT%H:%M:%S'))

datetime.timedelta(seconds=10333)

In [44]:
df['updated'].tolist()[-1].split("+")

['2020-08-06T21:07:47', '05:30']

In [45]:
# from datetime import datetime

dt = datetime.datetime.strptime(df['updated'].tolist()[-1].split("+")[0], '%Y-%m-%dT%H:%M:%S')
dt

datetime.datetime(2020, 8, 6, 21, 7, 47)

In [46]:
dt = (datetime.datetime.strptime(df['end'].tolist()[3].split("+")[0], '%Y-%m-%dT%H:%M:%S')-datetime.datetime.strptime(df['start'].tolist()[3].split("+")[0], '%Y-%m-%dT%H:%M:%S'))

In [47]:
dt.seconds

7200

In [62]:
df_day_raw = defaultdict(list)
cols = ['day', 'project', 'project_hex_color', 'dur']

In [63]:
pd.DataFrame.from_dict(df_day_raw)

           day               project project_hex_color       dur
0   2020-10-01          College Work           #525266         0
1   2020-09-30     Books and Courses           #d92b2b  18000000
2   2020-09-29     Books and Courses           #d92b2b  14700000
3   2020-09-28     Books and Courses           #d92b2b  24514000
4   2020-09-27         Side Projects           #9e5bd9  16157000
5   2020-09-26                chores           #525266  20693000
6   2020-09-24     Books and Courses           #d92b2b  24124000
7   2020-09-23     Books and Courses           #d92b2b   4089000
8   2020-09-22                Kaggle           #e36a00   9026000
9   2020-09-21                Kaggle           #e36a00   5382000
10  2020-09-20                Kaggle           #e36a00   3600000
11  2020-09-19                Kaggle           #e36a00   2100000
12  2020-09-18                Kaggle           #e36a00  15922000
13  2020-09-17                Kaggle           #e36a00  25922000
14  2020-09-16                Kaggle           #e36a00   8176000
15  2020-09-15     Books and Courses           #d92b2b  19787000
16  2020-09-14          College Work           #525266  21235000
17  2020-09-12                Kaggle           #e36a00  17802000
18  2020-09-11                Kaggle           #e36a00  23507000
19  2020-09-10          College Work           #525266  22047000
20  2020-09-09          College Work           #525266  21000000
21  2020-09-08          College Work           #525266  18600000
22  2020-09-07          College Work           #525266   9000000
23  2020-09-06          College Work           #525266  12900000
24  2020-09-05          College Work           #525266  21900000
25  2020-09-04               Overall           #bf7000   6328000
26  2020-09-03                Kaggle           #e36a00  12707000
27  2020-09-03                Kaggle           #e36a00   3934000
28  2020-09-02               Overall           #bf7000  16920000
29  2020-09-01          College Work           #525266  14634000
30  2020-08-31     Books and Courses           #d92b2b   1528000
31  2020-08-30     Books and Courses           #d92b2b  14282000
32  2020-08-29         Side Projects           #9e5bd9   8173000
33  2020-08-28         Side Projects           #9e5bd9         0
34  2020-08-27         Side Projects           #9e5bd9  11932000
35  2020-08-26         Side Projects           #9e5bd9  15820000
36  2020-08-25         Side Projects           #9e5bd9  17745000
37  2020-08-24         Side Projects           #9e5bd9  17672000
38  2020-08-23         Side Projects           #9e5bd9  22780000
39  2020-08-22        Wiki For Nerds           #2da608   7388000
40  2020-08-21     Googling/Browsing           #06a893  10505000
41  2020-08-20     Books and Courses           #d92b2b   6049000
42  2020-08-19     Books and Courses           #d92b2b   5324000
43  2020-08-18     Googling/Browsing           #06a893   6262000
44  2020-08-17     Books and Courses           #d92b2b   8612000
45  2020-08-16     Books and Courses           #d92b2b  17712117
46  2020-08-14     Googling/Browsing           #06a893   4007000
47  2020-08-13     Books and Courses           #d92b2b  11066000
48  2020-08-12     Books and Courses           #d92b2b   7097000
49  2020-08-11  web development(WFN)           #d92b2b   7610000
50  2020-08-10     Books and Courses           #d92b2b  14539000
51  2020-08-07     Books and Courses           #d92b2b   8477000
52  2020-08-06     Books and Courses           #d92b2b         0

In [79]:
df.columns.tolist()

['description',
 'start',
 'end',
 'updated',
 'dur',
 'project',
 'project_hex_color']